In [34]:
import pandas as pd
df = pd.read_csv('/content/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Richard Martinez #1,male,37.0,0,0,349909,21.6107,NaN,S
1,2,0,3,William Henry #2,male,28.1,1,0,PP 9549,14.8099,G6,S
2,3,0,2,Michael Brown #3,male,39.1,0,0,A/5. 2151,31.0070,C123,C
3,4,1,1,Susan Moore #4,female,51.3,2,0,113803,72.0536,NaN,S
4,5,1,2,Mrs Futrelle #5,female,26.7,0,0,113788,33.6019,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4055,2456,0,2,Farred Chehab #2456,male,52.6,0,0,PP 9549,21.0257,NaN,S
4056,187,0,3,Anna McGowan #187,female,19.4,0,0,PP 9549,18.3885,NaN,S
4057,691,1,1,Joseph Fynney #691,male,27.8,3,0,347742,63.6625,NaN,S
4058,2715,0,3,Dorothy Anderson #2715,female,21.5,0,0,113803,28.8933,NaN,C
4059,937,0,3,Lalio Todoroff #937,male,21.1,2,1,17463,10.9380,NaN,S

In [35]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Richard Martinez #1,male,37.0,0,0,349909,21.6107,NaN,S
1,2,0,3,William Henry #2,male,28.1,1,0,PP 9549,14.8099,G6,S
2,3,0,2,Michael Brown #3,male,39.1,0,0,A/5. 2151,31.0070,C123,C
3,4,1,1,Susan Moore #4,female,51.3,2,0,113803,72.0536,NaN,S
4,5,1,2,Mrs Futrelle #5,female,26.7,0,0,113788,33.6019,NaN,S

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4060 entries, 0 to 4059
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  4060 non-null   int64
 1   Survived     4060 non-null   int64
 2   Pclass       4060 non-null   int64
 3   Name         4060 non-null   object
 4   Sex          4060 non-null   object
 5   Age          3731 non-null   float64
 6   SibSp        4060 non-null   int64
 7   Parch        4060 non-null   int64
 8   Ticket       4060 non-null   object
 9   Fare         4060 non-null   float64
 10  Cabin        913 non-null    object
 11  Embarked     4018 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 380.8+ KB

In [ ]:
df.describe()

In [37]:
df.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             329
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin          3147
Embarked         42
dtype: int64

In [38]:
df.fillna(0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Richard Martinez #1,male,37.0,0,0,349909,21.6107,0,S
1,2,0,3,William Henry #2,male,28.1,1,0,PP 9549,14.8099,G6,S
2,3,0,2,Michael Brown #3,male,39.1,0,0,A/5. 2151,31.0070,C123,C
3,4,1,1,Susan Moore #4,female,51.3,2,0,113803,72.0536,0,S
4,5,1,2,Mrs Futrelle #5,female,26.7,0,0,113788,33.6019,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4055,2456,0,2,Farred Chehab #2456,male,52.6,0,0,PP 9549,21.0257,0,S
4056,187,0,3,Anna McGowan #187,female,19.4,0,0,PP 9549,18.3885,0,S
4057,691,1,1,Joseph Fynney #691,male,27.8,3,0,347742,63.6625,0,S
4058,2715,0,3,Dorothy Anderson #2715,female,21.5,0,0,113803,28.8933,0,C
4059,937,0,3,Lalio Todoroff #937,male,21.1,2,1,17463,10.9380,0,S

In [39]:
df.duplicated().sum()

np.int64(60)

In [40]:
df.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Richard Martinez #1,male,37.0,0,0,349909,21.6107,NaN,S
1,2,0,3,William Henry #2,male,28.1,1,0,PP 9549,14.8099,G6,S
2,3,0,2,Michael Brown #3,male,39.1,0,0,A/5. 2151,31.0070,C123,C
3,4,1,1,Susan Moore #4,female,51.3,2,0,113803,72.0536,NaN,S
4,5,1,2,Mrs Futrelle #5,female,26.7,0,0,113788,33.6019,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,1,3,Richard Martinez #3996,male,42.2,4,0,113788,25.0352,NaN,S
3996,3997,1,3,Laina Heikkinen #3997,female,14.0,0,0,244373,29.9690,NaN,S
3997,3998,0,1,John Johnson #3998,male,41.5,0,0,STON/O2. 3101282,91.4885,NaN,S
3998,3999,1,3,Anna McGowan #3999,female,29.1,1,1,2649,19.4742,NaN,S
3999,4000,0,3,Barbara Brown #4000,female,31.0,0,0,237736,20.0449,C123,Q